//actions for users
export const LOADING_CATEGORY_PRODUCT = "LOADING_CATEGORY_PRODUCT";
export const CREATE_CATEGORY_PRODUCT = "CREATE_CATEGORY_PRODUCT";
export const UPDATE_CATEGORY_PRODUCT = "UPDATE_CATEGORY_PRODUCT";
export const DELETE_CATEGORY_PRODUCT = "DELETE_CATEGORY_PRODUCT";
export const SEARCH_CATEGORY_PRODUCT = "SEARCH_CATEGORY_PRODUCT";
export const GET_CATEGORY_PRODUCT = "GET_CATEGORY_PRODUCT";
export const GET_SEARCH_CATEGORY_PRODUCT = "GET_ALL_CATEGORY_PRODUCT";
export const GET_ALL_CATEGORY_PRODUCT = "GET_ALL_CATEGORY_PRODUCT";
export const NO_DATA_CATEGORY_PRODUCT = "NO_DATA_CATEGORY_PRODUCT";
export const ERROR_CATEGORY_PRODUCT = "ERROR_CATEGORY_PRODUCT";