//actions for users
export const LOADING_OPERATIONBILL = "LOADING_OPERATIONBILL";
export const CREATE_OPERATIONBILL = "CREATE_OPERATIONBILL";
export const UPDATE_OPERATIONBILL = "UPDATE_OPERATIONBILL";
export const DELETE_OPERATIONBILL = "DELETE_OPERATIONBILL";
export const SEARCH_OPERATIONBILL = "SEARCH_OPERATIONBILL";
export const GET_OPERATIONBILL = "GET_OPERATIONBILL";
export const GET_SEARCH_OPERATIONBILL = "GET_ALL_OPERATIONBILL";
export const GET_ALL_OPERATIONBILL = "GET_ALL_OPERATIONBILL";
export const NO_DATA_OPERATIONBILL = "NO_DATA_OPERATIONBILL";
export const ERROR_OPERATIONBILL = "ERROR_OPERATIONBILL";
export const UPDATE_CODE_ERROR_OPERATIONBILL = "UPDATE_CODE_ERROR_OPERATIONBILL";