//actions for users
export const LOADING_PAYMENTTYPE = "LOADING_PAYMENTTYPE";
export const CREATE_PAYMENTTYPE = "CREATE_PAYMENTTYPE";
export const UPDATE_PAYMENTTYPE = "UPDATE_PAYMENTTYPE";
export const DELETE_PAYMENTTYPE = "DELETE_PAYMENTTYPE";
export const SEARCH_PAYMENTTYPE = "SEARCH_PAYMENTTYPE";
export const GET_PAYMENTTYPE = "GET_PAYMENTTYPE";
export const GET_PAYMENTHASEGRESS = "GET_PAYMENTHASEGRESS";
export const GET_SEARCH_PAYMENTTYPE = "GET_SEARCH_PAYMENTTYPE";
export const GET_ALL_PAYMENTTYPE = "GET_ALL_PAYMENTTYPE";
export const NO_DATA_RAYMENTTYPE = "NO_DATA_PAYMENTTYPE";
export const ERROR_PAYMENTTYPE = "ERROR_PAYMENTTYPE";
export const CLEAN_PAYMENTHASEGRESS = "CLEAN_PAYMENTHASEGRESS";
