//actions for users
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_SEARCH_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const NO_DATA_RPOVIDER = "NO_DATA";
export const ERROR_PRODUCT = "ERROR_PRODUCT";
export const UPDATE_CODE_ERROR_PRODUCT = "UPDATE_CODE_ERROR_PRODUCT";
