//actions for users
export const LOADING_PRODUCT_DELIVERY = "LOADING_PRODUCT_DELIVERY";
export const CREATE_PRODUCT_DELIVERY = "CREATE_PRODUCT_DELIVERY";
export const UPDATE_PRODUCT_DELIVERY = "UPDATE_PRODUCT_DELIVERY";
export const DELETE_PRODUCT_DELIVERY = "DELETE_PRODUCT_DELIVERY";
export const SEARCH_PRODUCT_DELIVERY = "SEARCH_PRODUCT_DELIVERY";
export const GET_PRODUCT_DELIVERY = "GET_PRODUCT_DELIVERY";
export const GET_SEARCH_PRODUCT_DELIVERY = "GET_SEARCH_PRODUCT_DELIVERY";
export const GET_ALL_PRODUCT_DELIVERY = "GET_ALL_PRODUCT_DELIVERY";
export const GET_PRODUCT_HAS_DELIVERY = "GET_PRODUCT_HAS_DELIVERY";
export const NO_DATA_PRODUCT_DELIVERY = "NO_DATA_PRODUCT_DELIVERY";
export const ERROR_PRODUCT_DELIVERY = "ERROR_PRODUCT_DELIVERY";
export const UPDATE_CODE_ERROR_PRODUCT_DELIVERY = "UPDATE_CODE_ERROR_PRODUCT_DELIVERY";
