//actions for users
export const LOADING_PROVIDER = "LOADING_PROVIDER";
export const CREATE_PROVIDER = "CREATE_PROVIDER";
export const UPDATE_PROVIDER = "UPDATE_PROVIDER";
export const DELETE_PROVIDER = "DELETE_PROVIDER";
export const SEARCH_PROVIDER = "SEARCH_PROVIDER";
export const GET_PROVIDER = "GET_PROVIDER";
export const GET_SEARCH_PROVIDER = "GET_ALL_PROVIDER";
export const GET_ALL_PROVIDER = "GET_ALL_PROVIDER";
export const NO_DATA_RPOVIDER = "NO_DATA";
export const ERROR_PROVIDER = "ERROR_PROVIDER";