//actions for users
export const LOADING_REVENUE = "LOADING_REVENUE";
export const CREATE_REVENUE = "CREATE_REVENUE";
export const CREATE_REVENUE_CLOSURE = "CREATE_REVENUE_CLOSURE";
export const CREATE_REVENUE_OTHER = "CREATE_REVENUE_OTHER";
export const UPDATE_REVENUE = "UPDATE_REVENUE";
export const UPDATE_REVENUE_CLOSURE = "UPDATE_REVENUE_CLOSURE";
export const UPDATE_REVENUE_OTHER = "UPDATE_REVENUE_OTHER";
export const DELETE_REVENUE = "DELETE_REVENUE";
export const SEARCH_REVENUE = "SEARCH_REVENUE";
export const GET_REVENUE = "GET_REVENUE";
export const GET_SEARCH_REVENUE = "GET_ALL_REVENUE";
export const GET_ALL_REVENUE = "GET_ALL_REVENUE";
export const NO_DATA_REVENUE = "NO_DATA";
export const ERROR_REVENUE = "ERROR_REVENUE";
export const UPDATE_CODE_ERROR_REVENUES = "UPDATE_CODE_ERROR_REVENUES";
export const GET_SEARCH_REVENUE_CLOSURE = "GET_SEARCH_REVENUE_CLOSURE";
export const GET_SEARCH_REVENUE_STADISTIC = "GET_SEARCH_REVENUE_STADISTIC";
export const GET_SEARCH_REVENUE_OTHER = "GET_SEARCH_REVENUE_OTHER";

